// Code generated by MockGen. DO NOT EDIT.
// Source: zet.go

// Package zetdao is a generated GoMock package.
package zetdao

import (
	context "context"
	reflect "reflect"

	model "github.com/anguloc/zet/internal/app/repo/zetdao/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// InsertRequest mocks base method.
func (m *MockRepo) InsertRequest(ctx context.Context, data *model.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRequest", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRequest indicates an expected call of InsertRequest.
func (mr *MockRepoMockRecorder) InsertRequest(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRequest", reflect.TypeOf((*MockRepo)(nil).InsertRequest), ctx, data)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// InsertRequest mocks base method.
func (m *MockWriter) InsertRequest(ctx context.Context, data *model.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRequest", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRequest indicates an expected call of InsertRequest.
func (mr *MockWriterMockRecorder) InsertRequest(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRequest", reflect.TypeOf((*MockWriter)(nil).InsertRequest), ctx, data)
}
